### ISSUE TITLE
package.json: move non-runtime deps to devDependencies

### ISSUE THREAD

**Issue by melekes** [cosmos/fundraiser#2]
If I am understanding it correctly, only a few of the dependencies listed in "dependencies" section are actually runtime deps (e.g. `vue-*`).

Given that some of the build dependencies have serious vulnerabilities https://snyk.io/test/github/cosmos/fundraiser, maybe it makes sense to mark/move them to "devDependencies"?

List of vulnerabilities discovered by snyk.io:
```
shelljs - Command Injection
nightwatch - Regular Expression Denial of Service, Remote Code Execution, Cross-Site Scripting, Denial of Service
karma - Insecure Randomness
phantomjs-prebuilt and karma-phantomjs-launcher - Uninitialized Memory Exposure
```

**Comment by mappum** [comment]
Hey @melekes, I didn't see this issue until just now.

Since this repo is just the web app and is not being `require`d as a module by other code, putting the deps in `devDependencies` won't make a difference. When we build the client-side JS using Webpack, only the libraries which get `require`d in the code are bundled for the user, so none of the vulnerable dependencies you listed are run in the users' browsers.
